name: Deploy Frontend to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Frontend to VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Pull the latest changes from GitHub
            cd hosting-fe
            git pull origin main
            
            # Navigate to backend to trigger orchestrated rebuild
            cd ../hosting-be
            docker-compose up -d --build
